<?php


// $disableTabs = (isset($_GET['disableTabs']) && $_GET['disableTabs'] === "false") ? false : true;
$_config = [
    'rcv.fieldQuestion' => env ('RCV_FIELD_QUESTION','field_22941'),
    'rcv.legalRepresentative' => env ('RCV_LEGAL_REPRESENTATIVE','field_22997'),
    'rcv.addLegalRepresentative' => env ('RCV_ADD_LEGAL_REPRESENTATIVE','field_22994'),
    'rcv.nameCulturePoint' => env('RCV_NAME_CULTURE_POINT', 'field_22971'),
    'rcv.namePontoColletivo' => env('RCV_NOME_PONTO_COLLETIVO', 'field_22969'),
    'rcv.nomePontaoDeCultura' => env('RCV_NOME_PONTAO_DE_CULTURA', 'field_22976'),
    'rcv.postalCode' => env ('RCV_POSTAL_CODE','field_22966'),
    'rcv.addressSet' => env ('RCV_ADDRESS_SET','field_22897'),
    'rcv.state' => env ('RCV_STATE','field_22888'),
    'rcv.publicPlace' => env ('RCV_PUBLIC_PLACE','field_22891'),
    'rcv.addressNumber' => env ('RCV_ADRESSNUMBER','field_22959'),
    'rcv.cityOfAddress' => env ('RCV_CITY_OF_ADDRESS','field_22963'),
    'rcv.organizationIsBrazil' => env ('RCV_ORGANIZATION_IS_BRAZIL','field_22926'),
    'rcv.country' => env ('RCV_COUNTRY','field_22958'),
    'rcv.questionResponse' => env ('RCV_QUESTION_RESPONSE','Sim. Estou ciente de que a minha certificação dependerá da avaliação pela Comissão de Seleção do edital da Cultura Viva em que estou concorrendo.'),
    'rcv.questionNoResponse' => env('RCV_QUESTION_NO_RESPONSE','Não. Estou ciente de que esta inscrição será avaliada pela Comissão de Certificação do Cadastro Nacional.'),
    'rcv.disableRegistrationUpdateButtons' => env('RCV_DISABLE_REGISTRATIONS_UPDATE_BUTTONS', false),
    'app.siteName' => env('RCV_SITE_NAME', 'Cultura Viva'),
    'rcv.email' => 'suporte.culturaviva@cultura.gov.br',
    'rcv.seals' => env('RCV_SEALS', '6,101,105,116,117'),
    'rcv.opportunityId' => env('RCV_OPPORTUNITY_ID', 5386),
    'rcv.disableTabs' => env('RCV_DISABLE_TABS', false),
    'rcv.disablePnabOpportunity' => env('RCV_DISABLE_PNAB_OPPORTUNITY', false),
    'rcv.disableDataDashboard' => env('RCV_DISABLE_DATA_DASHBOARD', false),
    'rcv.pnabOpportunityId' => env('RCV_PNAB_OPPORTUNITY_ID', 5388),
    'rcv.pnabOpportunityAttachmentId' => env('RCV_PNAB_OPPORTUNITY_ATTACHMENT_ID', '10428'),
    'rcv.pnabOpportunityUrl' => env('RCV_PNAB_OPPORTUNITY_URL', 'https://mapas-minc.testes.map.as/oportunidade/'),
    'rcv.phantomUserId' => env('RCV_PHANTOM_USER_ID', 510680),
    'rcv.categoriesMap' => [
        'pontao' => 'Pontão de Cultura (entidade com CNPJ)',
        'ponto-entidade' => 'Ponto de Cultura (entidade com CNPJ)',
        'ponto-coletivo' => 'Ponto de Cultura (coletivo sem CNPJ)',
    ],
    'rcv.rangesMap' => [
        'cadastro' => 'Cadastro',
        'alterar-cnpj' => 'Alteração de CNPJ',
        'alterar-organizacao' => 'Alteração do tipo de organização',
        'desativar-ponto' => 'Desativar ponto',
        'cadastro-via-edital' => 'Cadastro via edital',
    ],
    'rcv.toggleCNPJFakeApi' => env('RCV_TOGGLE_CNPJ_FAKE_API', false),
    'rcv.disableApiFilters' => env('RCV_DISABLE_API_FILTERS', false),
    'rcv.verificationSeals' => [
        'pontao' => env('RCV_SEAL_CERTIFIER_ID_PONTAO', '101'),
        'ponto' => env('RCV_SEAL_CERTIFIER_ID_PONTO', '6'),
        'desativado' => env('RCV_SEAL_CERTIFIER_ID_DISABLED', '116'),
    ],
    'rcv.importerSeal' => env('RCV_IMPORTER_SEAL', 105),
    'rcv.waitingUpdateSeal' => env('RCV_WAITING_UPDATE_SEAL', 117),
    'rcv.apiReturnedFieldsUsed' => [ // Campo retornados da API que são salvos no cadastro já no retorno
        'nomeCompleto' => ['disable' => true, 'rfDataField' => 'nomeEmpresarial'],
        'emailPublico' => ['disable' => false, 'rfDataField' => 'correioEletronico'],
        'cnpj' => ['disable' => true, 'rfDataField' => 'ni'],
        'En_Municipio' => ['disable' => false, 'rfDataField' => 'endereco.municipio.descricao'],
        'En_Estado' => ['disable' => false, 'rfDataField' => 'endereco.uf'],
        'telefone1' => ['disable' => false, 'rfDataField' => 'telefones?.[0]'],
    ],
    'rcv.realizaAtividadesField' => env('RCV_REALIZA_ATIVIDADES_FIELD', ''),
    'rcv.removeFileFields' => [
        'rfc_10424',
        'rfc_10415',
        'rfc_10417',
        'rfc_10418'
    ],
    // textos customizados
    'text:search.agents.view(agent).title' => "PONTOS E PONTÕES DE CULTURA", 
    'text:search.agents.search-list.agents' => "Pontos e Pontões", 
    'text:search.agents.view(agent).agents' => "Pontos e Pontões",
    // 'text:agent.single.rcv-entity-header.certificateButton' => "Certificado",
    'text:registration.view.entity-field-location.privacy-label--yes' => "Sim (estou ciente de que este endereço aparecerá no perfil da organização no Mapa da Rede Cultura Viva e, como espaço, do Mapa da Cultura, caso seja certificada como Ponto ou Pontão de Cultura)",
    'text:registration.view.registration-field-address.nome endereço' => "Nome do espaço, se houver.",

    'text:panel.registrations.registration-card.registration-number-label' => 'Número do cadastro',
    'text:panel.registrations.registration-card.create-timestamp-label' => 'Data de cadastro',
    'text:opportunity.single.registration-card.create-timestamp-label' => 'Data de cadastro',

    'text:panel.registrations.registration-card.owner-label' => 'Agente responsável',
    'text:opportunity.single.registration-card.owner-label' => 'Agente responsável',

    'text:panel.registrations.registration-card.status-label' => 'Status do cadastro',
    'text:opportunity.single.registration-card.status-label' => 'Status do cadastro',

    'text:panel.registrations.registration-card.coletive-label' => 'Nome da organização',
    'text:opportunity.single.registration-card.coletive-label' => 'Nome da organização',

    // Alteração de inscrição para cadastro
    'text:panel.registrations.view(registrations).my-registrations' => 'Cadastros',
    'text:view(registrations).my-registrations-records' => 'Nesta seção, você pode adicionar e gerenciar seus cadastros.',
    'text:panel.registrations.view(registrations).my-registrations-records' => 'Gerenciar cadastros',
    'text:registration-card.my-records-numbers' => 'Número de cadastro:',
    'text:registration-autosave-notification.registration_alert_message' => 'Os dados do seu cadastro serão salvos automaticamente a cada {{resultTime}} segundos.',
    'text:panel--last-registrations.recent_registrations' => 'Cadastros recentes',
    'text:panel--last-registrations.registration_date' => 'Data do cadastro',
    'text:registration-card.notification_deletion' => 'Você realmente deseja excluir o cadastro',
    'text:registration-card.registration_removed' => 'Cadastro removido',
    'text:panel--registration-tabs.registrations_not_completed' => 'Você tem cadastros não finalizados. Acesse a aba',
    'text:view(single).registration_number' => 'Nº do cadastro',
    'text:view(single).registration_category' => 'Categoria do cadastro',
    'text:view(single).registration_status' => 'Status do cadastro',
    'text:opportunity-phases-timeline.phase_registration' => 'Fase do cadastro',
    'text:view(single).registration_form' => 'Ficha do cadastro',
    'text:registration.view.view(single).my_records_form' => 'Cadastro',
    'text:view(single).registration_info__footer' => 'Cadastro realizado em',
    'text:registration-actions.registration_registrationEdit' => 'Ao enviar seu cadastro você afirma que concorda com os termos da',
    'text:opportunity.single.opportunity-subscription-list.subscription-list-subtitle' => ' ',
    'text:entity-status.agent-status--draft' => 'Este agente está em modo de rascunho porque seu cadastro ainda está em análise. A publicação será feita automaticamente após a aprovação.',

    'rcv.SpreadsheetColumnsLabels' => [
        'singleUrl' => ['label' => 'Identificação e link para perfil', 'public' => true],
        'tipoPonto' => ['label' => 'Tipo', 'public' => true],
        'cnpj' => ['label' => 'CNPJ', 'public' => true],
        'ownerName' => ['label' => 'Responsável', 'public' => true],
        'cpf' => ['label' => 'CPF do responsável', 'public' => false],
        'seals' => ['label' => 'Certificação', 'public' => true],
        'rcv_cad_updateTimestamp' => ['label' => 'Última atualização', 'public' => true],
        'nomeCompleto' => ['label' => 'Organização', 'public' => true],
        'name' => ['label' => 'Nome do Ponto ou Pontão', 'public' => true],
        'emailPublico' => ['label' => 'Email público', 'public' => true],
        'telefonePublico' => ['label' => 'Telefone público', 'public' => true],
        'longDescription' => ['label' => 'Apresentação', 'public' => true],
        'facebook' => ['label' => 'Facebook da organização', 'public' => false],
        'tiktok' => ['label' => 'Tiktok da organização', 'public' => false],
        'instagram' => ['label' => 'Instagram da organização', 'public' => false],
        'rcv_links_coletivo' => ['label' => 'Outros links da organização', 'public' => false],
        'dataDeNascimento' => ['label' => 'Início das atividades', 'public' => false],
        'rcv_atividade_gratuita' => ['label' => 'Atividades gratuitas', 'public' => false],
        'tipoReconhecimento' => ['label' => 'Reconhecimento anterior', 'public' => false],
        'rcv_selos_solicitados' => ['label' => 'Solicita outro selo', 'public' => false],
        'rcv_patrimonio_hiostorico' => ['label' => 'Patrimônio em qual instância', 'public' => false],
        'comunidadesTradicional' => ['label' => 'Povo ou Comunidade Tradicional', 'public' => true],
        'comunidadesTradicionalOutros' => ['label' => 'OUTRO Povo ou Comunidade Tradicional', 'public' => false],
        'rcv_etnia' => ['label' => 'Etnia indígena', 'public' => true],
        'rcv_org_brasil' => ['label' => 'Sediada no Brasil', 'public' => false],
        'paisPontaPontao' => ['label' => 'País', 'public' => true],
        'cepPontaPontao' => ['label' => 'CEP', 'public' => true],
        'En_Nome_LogradouroPontaPontao' => ['label' => 'Logradouro', 'public' => true],
        'En_NumPontaPontao' => ['label' => 'Número', 'public' => true],
        'En_MunicipioPontaPontao' => ['label' => 'Município', 'public' => true],
        'En_EstadoPontaPontao' => ['label' => 'Estado', 'public' => true],
        'endereco' => ['label' => '22897 - Qual é o endereço fixo ou da sede da organização, ou endereço de referência?', 'public' => false],
        'tem_sede' => ['label' => 'Situação da sede', 'public' => false],
        'rcv_sede_outros' => ['label' => 'Outra situação da sede', 'public' => false],
        'sede_realizaAtividades' => ['label' => '22978 - A organização realiza atividades culturais no espaço da sede?', 'public' => false],
        'rcv_sede_realizaAtividades_outros' => ['label' => '22894 - A organização realiza atividades em outro(s) espaço(s)?', 'public' => false],
        'rcv_sede_realizaAtividades_outros_lista' => ['label' => '22937 - Se sim, qual insira endereço do(s) espaço(s)?', 'public' => false],
        'rcv_territorio_direto_org' => ['label' => '22936 - Indique o território de atuação cultural direta da organização:', 'public' => false],
        'rcv_local_atuacao_org' => ['label' => 'Local(is) de atuação', 'public' => true],
        'rcv_localizacao_sede_org' => ['label' => 'Localização da sede ou espaço de encontro', 'public' => true],
        'rcv_atividades_realizadas_neste_territorio' => ['label' => 'Atuação em territórios vulneráveis', 'public' => true],
        'rcv_medidas_acessibilidade_disponiveis' => ['label' => 'Acessibilidade arquitetônica', 'public' => true],
        'rcv_medidas_acessibilidade_disponiveis_outras' => ['label' => 'OUTRA(s) arquitetônica', 'public' => false],
        'rcv_medidas_acessibilidade_comunicacional_outras' => ['label' => 'OUTRA(s) comunicacional', 'public' => false],
        'rcv_medidas_acessibilidade_comunicacional' => ['label' => 'Acessibilidade comunicacional', 'public' => true],
        'rcv_medidas_acessibilidade_atitudinal' => ['label' => 'Acessibilidade atitudinal', 'public' => true],
        'rcv_medidas_acessibilidade_atitudinal_outras' => ['label' => 'OUTRA(s) atitudinal', 'public' => false],
        'rcv_faixa_etaria' => ['label' => 'Faixa etária do público que participa das ações', 'public' => true],
        'rcv_deficiencia' => ['label' => 'Público PCD', 'public' => true],
        'rcv_publico_deficiencia' => ['label' => 'OUTRA deficiência', 'public' => false],
        'rcv_deficiencia_outros' => ['label' => '22968 - Se OUTRA deficiência, qual?', 'public' => false],
        'rcv_publicos_prioritarios' => ['label' => 'Públicos prioritários', 'public' => true],
        'rcv_publico_outros' => ['label' => 'OUTRO público específico', 'public' => false],
        'rcv_publico_comunidades_tradicionais' => ['label' => 'Povos e Comunidades Tradicionais que participam das ações', 'public' => true],
        'rcv_publico_outros_descricao' => ['label' => 'Outro público prioritário', 'public' => false],
        'rcv_publico_povos_indigenas_etinia' => ['label' => 'Etnias indígenas que participam das ações', 'public' => true],
        'rcv_publico_envolvido' => ['label' => 'Descrição do público', 'public' => false],
        'rcv_acoes_da_organizacao' => ['label' => 'Participantes POR MÊS', 'public' => false],
        'rcv_meses_regulares_organização' => ['label' => 'Meses de atividades por ano', 'public' => false],
        'acao_estruturante' => ['label' => 'Ações estruturantes da PNCV', 'public' => true],
        'acao_estruturante_outra' => ['label' => 'Outras ações estruturantes', 'public' => true],
        'acao_estruturante_outra_descreva' => ['label' => '22957 - Se optou por OUTRA, descreva.', 'public' => false],
        'rcv_principais_segmentos' => ['label' => 'Principais áreas de atuação', 'public' => true],
        'rcv_atuacao_demais_segmentos' => ['label' => 'Demais áreas de atuação', 'public' => true],
        'redePertencente' => ['label' => '22961 - A organização atua em rede, participando de ações conjuntas com outros Pontos ou Pontões de Cultura, de mobilização, articulação e/ou formação?', 'public' => false],
        'rcv_atuacao_descreva_atividade' => ['label' => '22893/22996 - Se sim, descreva que tipo de atividades realiza em rede realizadas e com quais parcerias:', 'public' => false],
        'rcv_atuacao_ods' => ['label' => '23001 - A organização contribui para os Objetivos de Desenvolvimento Sustentável (ODS)? Se sim, escolha em ordem de prioridade.', 'public' => false],
        'rcv_quantidade_trabalhadores' => ['label' => '#310 - Quantos trabalhadores da cultura estão diretamente envolvidos nas atividades da organização?', 'public' => false],
        'rcv_deficientes_organizacao' => ['label' => 'Trabalhadores PCD envolvidos', 'public' => false],
        'rcv_quantidade_deficientes' => ['label' => 'Quantos PCD', 'public' => false],
        'rcv_deficiencias_trabalhadores' => ['label' => 'Quais deficiências dos trabalhadores', 'public' => false],
        'rcv_deficiencias_trabalhadores_outra' => ['label' => 'Outra deficiência', 'public' => false],
        'rcv_ocupacoes_organizacao' => ['label' => 'Ocupações/profissões', 'public' => false],
        'rcv_ocupacoes_organizacao_outra' => ['label' => 'Outra ocupação', 'public' => false],
        'rcv_faixa_etaria_organizacao' => ['label' => 'Faixa(s) etária(s) da equipe', 'public' => false],
        'rcv_escolaridade_equipe' => ['label' => 'Escolaridade(s) da equipe?', 'public' => false],
        'rcv_valor_min_organizacao' => ['label' => 'Valor anual mínimo necessário', 'public' => false],
        'rcv_recursos_publicos_organizacao' => ['label' => 'Fomento cultura últimos cinco anos', 'public' => false],
        'foiFomentado' => ['label' => 'Fomento à Cultura Viva', 'public' => false],
        'tipoFomento' => ['label' => 'Tipo apoio/fomento Cultura Viva', 'public' => false],
        'esferaFomento' => ['label' => 'Esfera fomento Cultura Viva', 'public' => false],
        'rcv_valor_total_organizacao' => ['label' => 'Arrecadado último ano', 'public' => false],
        'rcv_concorrendo_edital' => ['label' => 'Concorrendo em edital', 'public' => false],
        'rcv_edital' => ['label' => 'Edital em que está concorrendo', 'public' => false],
        'rcv_edital_fomento' => ['label' => '#332 - Qual estado concorreu?', 'public' => false],
        'rcv_fomento_municipal' => ['label' => '#529 - Qual o estado?', 'public' => false],
        'rcv_meses_media_ano_org' => ['label' => '22998 - Quantas pessoas, em média, participam das ações da organização POR ANO?', 'public' => false],
        'rcv_fomento_distrital' => ['label' => '#332 - Qual estado concorreu?', 'public' => false],
        'outrosSelos' => ['label' => 'Outros Selos', 'public' => true],
        "location" => ["label" => "Localização"],
        "publicLocation" => ["label" => "Localização Pública"],
    ],
];

if(php_sapi_name() != "cli"){

    $routes = $this->config['routes'] ?? [];

    $new_routes = [
        'novo-cadastro' => ['opportunity', $_config['rcv.opportunityId']],
        'importacao' => ['opportunity', $_config['rcv.pnabOpportunityId']],
    ];

    foreach($new_routes as $route => $target) {
        $routes['shortcuts'][$route] = [$target[0], 'single', [$target[1]]];
    }

    $routes['shortcuts']['mapa'] = ['search', 'agents'];
    $routes['shortcuts']['certificado'] = ['seal', 'sealRelation'];
    $routes['shortcuts']['meus-cadastros'] = ['panel', 'registrations'];
    unset($routes['shortcuts']['agentes']);
    unset($routes['shortcuts']['minhas-inscricoes']);

    $_config['routes'] = $routes;
}

return $_config;